# Generated by Django 4.2 on 2024-03-14 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
        ('users', '0003_alter_user_options_remove_user_username_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(blank=True, null=True, verbose_name='Дата платежа')),
                ('summ_pay', models.PositiveIntegerField(blank=True, null=True, verbose_name='Сумма платежа')),
                ('way_pay', models.IntegerField(choices=[(0, 'Перевод на счет'), (1, 'Наличные')], default=0, verbose_name='способ оплаты')),
                ('pay_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.course', verbose_name='Оплаченный курс')),
                ('pay_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.lesson', verbose_name='Оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
