# Generated by Django 4.2 on 2024-04-01 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_enter',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 4, 1, 20, 32, 50, 978726), verbose_name='Дата последнего захода'),
        ),
    ]
