# Generated by Django 4.2 on 2024-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_enter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_enter',
        ),
    ]
