# Generated by Django 4.2 on 2024-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_remove_subscription_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=5000, verbose_name='цена за курс'),
        ),
    ]
