# Generated by Django 4.2 on 2024-03-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0008_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='product_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
